name: Continuous Integration

on:
    push:

jobs:
  checks:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
          - "3.10"
          - pypy-3.8
          - pypy-3.9
        os:
          - ubuntu-latest
          - macos-latest
          # - windows-latest
    runs-on:  ${{ matrix.os }}
    name: ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: pip install poetry
      - run: poetry install --no-ansi
      - run: poetry run pytest --exitfirst --no-header --tb=no --assert=plain --numprocesses=auto tests.py
